server:
  port: 8892

spring:
  application:
    name: admin-server  # 用于指定注册到Eureka Server上的应用名称


# include 暴露端点 (不暴露时)
management:
  endpoints:
    web:
      exposure:
        include: "*"
    #  注释后 不显示 logfile 模块
    logfile:
      external-file: admin-log.log  #指向日志文件地址，需与LogBack配置的日志地址一致