server:
  port: 8761

spring:
  #应用名称
  application:
    name: discovery-eureka
  #用户认证
  security:
    user:
      name: admin #配置账户和密码
      password: admin
    basic:
      enabled: true  #开启基于Http basic的认证

eureka:
  client:
    # 是否将自己注册到Eureka Server，默认是true。由于当前应用就是Eureka Server，故设false
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认是true。由于这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故设false
    fetchRegistry: false
    serviceUrl:
      #设置与Eureka Server交互的地址。多个地址可使用，分隔。
      defaultZone: http://admin:admin@localhost:8761/eureka/



