server:
  port: 8884
spring:
  application:
      name: consumer  # 用于指定注册到Eureka Server上的应用名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@10.0.10.51:8761/eureka/,http://admin:admin@10.0.10.52:8761/eureka/,http://admin:admin@10.0.10.53:8761/eureka/
  instance:
    perfer-ip-address: true #将自己IP注册到Eureka Server

feign:
  hystrix:
    enabled: true #开启熔断器hystrix

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' #暴露hystrix监控端点
