server:
  port: 8887
spring:

  #用于指定注册到Eureka Server上的应用名称
  application:
      name: config-server  # 用于指定注册到Eureka Server上的应用名称

  #配置中心
  cloud:
    config:
      label: master #配置仓库的分支
      server:
        git:
          uri: https://github.com/jiaoxiangyu/springcloud-config.git #配置git仓库地址
          search-paths: /consumer #配置仓库路径 从对应应用名称的子目录中搜索配置, 可配置多个
          #username:  #访问git仓库的用户名
          #password:  #访问git仓库的用户密码
          clone-on-start: true #开启启动时直接从git获取配置

  #配置用户名和密码校验
  security:
    user:
      name: admin
      password: admin

  #rabbitmq相关配置
  rabbitmq:
    host: 10.0.10.52
    port: 5672
    username: admin
    password: admin

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@10.0.10.51:8761/eureka/,http://admin:admin@10.0.10.52:8761/eureka/,http://admin:admin@10.0.10.53:8761/eureka/
  instance:
    perfer-ip-address: true #将自己IP注册到Eureka Server


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh' #暴露bus刷新配置的端点

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


